# Generated by Django 5.0.2 on 2024-03-07 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('energy_consumption', models.FloatField()),
                ('transportation', models.FloatField()),
                ('waste_generation', models.FloatField()),
                ('water_usage', models.FloatField()),
                ('food_consumption', models.FloatField()),
                ('shopping_habits', models.FloatField()),
                ('housing', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='EnvironmentalImpact',
        ),
    ]
