# Generated by Django 5.0.2 on 2024-03-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportation',
            old_name='miles',
            new_name='distance',
        ),
        migrations.AlterField(
            model_name='transportation',
            name='mode',
            field=models.CharField(choices=[('car', 'Car'), ('bus', 'Bus'), ('train', 'Train'), ('plane', 'Plane'), ('bike', 'Bike'), ('walk', 'Walk'), ('other', 'Other')], max_length=255),
        ),
    ]
