# Generated by Django 5.0.2 on 2024-03-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0002_rename_miles_transportation_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastegeneration',
            name='frequency',
            field=models.CharField(default='Daily', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastegeneration',
            name='location',
            field=models.CharField(default='daily', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastegeneration',
            name='unit',
            field=models.CharField(default='Bags', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastegeneration',
            name='waste_type',
            field=models.CharField(default='Paper', max_length=255),
            preserve_default=False,
        ),
    ]
