# Generated by Django 5.0.2 on 2024-03-11 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0002_alter_environmentdata_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbonfootprintdata',
            options={'verbose_name_plural': 'Carbon Footprint Data'},
        ),
        migrations.AlterModelOptions(
            name='environmentdata',
            options={'ordering': ['-date_entered'], 'verbose_name_plural': 'Environment Data'},
        ),
    ]
