# Generated by Django 5.0.2 on 2024-03-12 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0003_alter_carbonfootprintdata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonfootprintdata',
            name='environment_data',
            field=models.ForeignKey(default=9000, on_delete=django.db.models.deletion.CASCADE, to='data_collection.environmentdata'),
            preserve_default=False,
        ),
    ]
