# Generated by Django 5.0.2 on 2024-03-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0003_wastegeneration_frequency_wastegeneration_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodconsumption',
            name='frequency',
            field=models.CharField(default='Daily', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='housing',
            name='location',
            field=models.CharField(default='House', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinghabits',
            name='frequency',
            field=models.CharField(default='Daily', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterusage',
            name='frequency',
            field=models.CharField(default='Daily', max_length=50),
            preserve_default=False,
        ),
    ]
