# Generated by Django 5.0.2 on 2024-03-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0005_carbonfootprint_carbonfootprintbreakdown_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbonfootprintbreakdown',
            name='user',
        ),
        migrations.RemoveField(
            model_name='carbonfootprintcomparison',
            name='user',
        ),
        migrations.DeleteModel(
            name='CarbonFootprint',
        ),
        migrations.DeleteModel(
            name='CarbonFootprintBreakdown',
        ),
        migrations.DeleteModel(
            name='CarbonFootprintComparison',
        ),
    ]
